#!/bin/sh
# Copies the app's own assets into public/: template previews, device-frame PNGs,
# the logo and the bundled DM Sans template font. public/ is fully regenerated by this script.
set -e
cd "$(dirname "$0")/.."
APP=../../screenshot
mkdir -p public/templates public/frames public/fonts public/audio
for d in "$APP"/Templates.bundle/*/; do
  name=$(basename "$d")
  # App Store previews may not name other platforms.
  [ "$name" = google-play ] && continue
  [ -f "$d/preview.png" ] && cp "$d/preview.png" "public/templates/$name.png"
done
for f in iphone17pro-deepblue-portrait iphone17pro-cosmicorange-portrait iphoneair-cloudwhite-portrait \
         iphone17-lavender-portrait ipadpro13-spacegray-portrait macbookair13-midnight-landscape; do
  cp "$APP/Assets.xcassets/DeviceFrames/$f.imageset/$f.png" public/frames/
done
sed "s/fill=\"black\"/fill=\"white\"/g" "$APP/Assets.xcassets/Logo.imageset/logo_dark.svg" > public/logo.svg
cp "$APP/Templates.bundle/shared/fonts/DMSans-VariableFont_opsz,wght.ttf" public/fonts/DMSans.ttf
ls public/templates | sed 's/\.png$//' | awk 'BEGIN{printf "export const TEMPLATE_NAMES = ["} {printf "%s\"%s\"", (NR>1?", ":""), $0} END{print "];"}' > src/templates.gen.ts
echo "assets ready"
