#!/usr/bin/env python3
"""Audit Screenshot Bro's app-interface String Catalog.

The catalog is generated by Xcode and populated by the translation scripts, so
this checker is intentionally read-only. It catches the localization regressions
that are easy to reintroduce from Swift code: missing target-language entries,
format placeholder drift, leaked translation-protection tokens, untranslated
English copy, and manual plural hacks such as `screenshot%@` or `image(s)`.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import xcstrings_format


CATALOG = Path(__file__).parent.parent / "screenshot" / "Localizable.xcstrings"
TARGET_LANGUAGES = ("de", "es", "fa", "fr", "ja", "ko", "pt-BR", "zh-Hans")

FORMAT_SPECIFIER_RE = re.compile(
    r"%(?:(?P<position>\d+)\$)?(?P<type>@|lld|ld|d|[0-9]*(?:\.[0-9]+)?[fF]|%)"
)
PROTECTION_TOKEN_RE = re.compile(r"\[\[(?:FMT|TERM)_\d+\]\]|\[\[SEP_BLOCK\]\]")
MANUAL_PLURAL_RE = re.compile(
    r"\b(?:screenshot|locale|version|field|language|item|image|file|set)%@"
    r"|\b(?:image|file|screenshot|field|locale|version|language|item|set)\(s\)"
)
ASCII_WORD_RE = re.compile(r"[A-Za-z]{2,}")

VERBATIM_ALLOWED = {
    "",
    "%",
    " · ",
    "-> %@",
    "%@ -> %@",
    "%@ · %@",
    "%@ · %@ -> %@",
    "%@ · %@: %@",
    "%lld",
    "%lld / %lld",
    "%lld of %lld",
    "%lld/%lld",
    "%lld%%",
    "%lld°",
    "%lld×%lld",
    "%lld × %lld px",
    "%lld pt",
    "%lld shapes",
    "1 version",
    "%lld versions",
    "Angular",
    "App",
    "Attributions",
    "Auto",
    "Automation",
    "Backup",
    "Base",
    "by izatrcsldssb",
    "Color",
    "Copyright",
    "Description",
    "Details",
    "Format",
    "General",
    "Image",
    "Images",
    "Inspector",
    "Invisible",
    "Legal",
    "Linear",
    "Material",
    "Medium",
    "Mode",
    "Name",
    "OK",
    "optional",
    "Orientation",
    "Paste",
    "Plan",
    "Points",
    "Portrait",
    "Position",
    "Pro: %@",
    "Quick Look",
    "Radial",
    "Radius",
    "Rectangle",
    "Regular",
    "RevenueCat ID",
    "Rotation",
    "Screenshot 1",
    "Screenshots",
    "Source",
    "Status",
    "Style",
    "SVGs",
    "System",
    "Text",
    "Turning it on",
    "Unchanged",
    "Upgrade",
    "version",
    "Version",
    "versions",
    "Website: [screenshotbro.app](https://screenshotbro.app)",
    "X: %lld%%",
    "Y: %lld%%",
    "Zoom",
    "API",
    "API Key",
    "App Store",
    "App Store Connect",
    "Beta",
    "H",
    "iCloud",
    "iOS",
    "iPad",
    "iPhone",
    "iPhone 17 Pro",
    "iPhone 17 Pro Max",
    "Issuer ID",
    "JPEG",
    "Key ID",
    "Mac",
    "macOS",
    "PNG",
    "Private Key (.p8)",
    "Pro",
    "RevenueCat",
    "Screenshot Bro",
    "Screenshot Bro Pro",
    "SVG",
    "W",
    "Xcode",
    "Google Play",
    "Import .p8 File…",
    "com.example.myapp",
    "© 2025 Your Company",
    "by Ibrahim.Bhl",
    "e.g. 57246542-96fe-1a63-e053-0824d011072a",
}


def normalized_specifiers(value: str) -> list[str]:
    specs: list[tuple[int, str, bool]] = []
    for index, match in enumerate(FORMAT_SPECIFIER_RE.finditer(value), start=1):
        if match.group(0) == "%%":
            continue
        position = int(match.group("position")) if match.group("position") else index
        specs.append((position, match.group("type"), match.group("position") is not None))
    if specs and all(positioned for _position, _type, positioned in specs):
        specs = sorted(specs, key=lambda item: item[0])
    return [f"%{specifier_type}" for _position, specifier_type, _positioned in specs]


def localized_values(localization: dict) -> list[str]:
    values: list[str] = []

    def collect(node: object) -> None:
        if isinstance(node, dict):
            string_unit = node.get("stringUnit")
            if isinstance(string_unit, dict) and isinstance(string_unit.get("value"), str):
                values.append(string_unit["value"])
            for key, value in node.items():
                if key != "stringUnit":
                    collect(value)
        elif isinstance(node, list):
            for value in node:
                collect(value)

    collect(localization)
    return values


def is_active(entry: dict, include_stale: bool) -> bool:
    return include_stale or entry.get("extractionState") != "stale"


def should_allow_verbatim(source: str) -> bool:
    if source in VERBATIM_ALLOWED:
        return True
    if not ASCII_WORD_RE.search(source):
        return True
    if source.startswith("http://") or source.startswith("https://"):
        return True
    return False


def audit(catalog: Path, include_stale: bool) -> list[str]:
    data = xcstrings_format.load(catalog)
    strings = data.get("strings", {})
    errors: list[str] = []

    for key, entry in strings.items():
        if not is_active(entry, include_stale):
            continue

        if MANUAL_PLURAL_RE.search(key):
            errors.append(f"manual plural anti-pattern in key: {key}")

        source_specs = normalized_specifiers(key)
        localizations = entry.get("localizations", {})
        for language in TARGET_LANGUAGES:
            localization = localizations.get(language)
            if not localization:
                errors.append(f"{language}: missing localization for {key}")
                continue

            values = localized_values(localization)
            if not values:
                errors.append(f"{language}: missing string value for {key}")
                continue

            for value in values:
                if PROTECTION_TOKEN_RE.search(value):
                    errors.append(f"{language}: unreplaced translation token in {key}: {value}")

                if MANUAL_PLURAL_RE.search(value):
                    errors.append(f"{language}: manual plural anti-pattern in {key}: {value}")

                value_specs = normalized_specifiers(value)
                if value_specs != source_specs:
                    errors.append(
                        f"{language}: placeholder mismatch for {key}: "
                        f"source={source_specs} translation={value_specs}"
                    )

                if value == key and not should_allow_verbatim(key):
                    errors.append(f"{language}: untranslated value for {key}")

    return errors


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog", type=Path, default=CATALOG)
    parser.add_argument("--include-stale", action="store_true")
    args = parser.parse_args()

    errors = audit(args.catalog, args.include_stale)
    if errors:
        print(f"localization audit failed with {len(errors)} issue(s):", file=sys.stderr)
        for error in errors[:200]:
            print(f"- {error}", file=sys.stderr)
        if len(errors) > 200:
            print(f"... {len(errors) - 200} more", file=sys.stderr)
        return 1

    print("localization audit passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
