#!/usr/bin/env python3
"""Populate Spanish translations in Localizable.xcstrings.

Also merges any keys found in Xcode's .stringsdata outputs that aren't
already in the catalog — works around xcodebuild CLI not running the
catalog-merge step every time.

Run from repo root:  python3 tools/translate_catalog.py
"""
import glob
import json
import sys
from pathlib import Path

CATALOG = Path(__file__).parent.parent / "screenshot" / "Localizable.xcstrings"
STRINGSDATA_GLOB = (
    "/Users/taras/Library/Developer/Xcode/DerivedData/"
    "screenshot-fjyqstlptltgswabxaalthsugfna/Build/Intermediates.noindex/"
    "screenshot.build/Debug/screenshot.build/Objects-normal/arm64/*.stringsdata"
)

# Keys intentionally NOT translated (identical in Spanish: format strings,
# brand names, identifiers, file extensions, attribution, examples).
KEEP_AS_IS = {
    "", " · ", "%", "-> %@", "%@ -> %@", "%@ · %@: %@", "%lld", "%lld / %lld",
    "%lld × %lld px", "%lld of %lld", "%lld/%lld", "%lld%%", "%lld°",
    "%lld×%lld", "%lld×%lld · %lld screenshot%@", "%lld pt", "%lld screenshot%@",
    "%lld screenshot%@ uploaded across %lld locale%@.", "%lld shapes",
    "%lld stops", "%lld more skipped item%@", "X: %lld%%", "Y: %lld%%",
    "PNG", "JPEG", "SVG", "RevenueCat", "Pro", "Beta", "API Key", "Issuer ID",
    "Key ID", "Private Key (.p8)", "Import .p8 File…", "App Store Connect",
    "iPhone 17 Pro", "by Ibrahim.Bhl", "© 2025 Your Company",
    "e.g. 57246542-96fe-1a63-e053-0824d011072a", "W", "H",
    "Switch to the base language (⌥⌘0)",
}

# English -> Spanish translations.
ES = {
    "3D device rotation is an experimental feature": "La rotación 3D de dispositivo es una función experimental",
    "3D Models": "Modelos 3D",
    "10-character key ID": "Key ID de 10 caracteres",
    "500 App Store Screenshot Templates": "500 plantillas de capturas para la App Store",
    "Accepted sizes": "Tamaños aceptados",
    "Actions": "Acciones",
    "Actual Size": "Tamaño real",
    "Add": "Añadir",
    "Add %@": "Añadir %@",
    "Add Element": "Añadir elemento",
    "Add Language": "Añadir idioma",
    "Add New Row Above": "Añadir fila arriba",
    "Add New Row Below": "Añadir fila debajo",
    "Add SVG": "Añadir SVG",
    "Add Screenshot": "Añadir captura",
    "Add Screenshot After": "Añadir captura después",
    "Add Screenshot Before": "Añadir captura antes",
    "Add another language to edit translations here.": "Añade otro idioma para editar traducciones aquí.",
    "Add at least two screenshots to stretch background across row.": "Añade al menos dos capturas para extender el fondo por toda la fila.",
    "Add new row": "Añadir fila",
    "Add screenshot": "Añadir captura",
    "Add shape": "Añadir forma",
    "Add templates to the app bundle.": "Añade plantillas al paquete de la app.",
    "Add this locale in App Store Connect, then refresh locales.": "Añade este idioma en App Store Connect y luego actualiza los idiomas.",
    "Add your Issuer ID, Key ID, and .p8 key in Settings → App Store Connect.": "Añade tu Issuer ID, Key ID y la clave .p8 en Ajustes → App Store Connect.",
    "Align": "Alinear",
    "Align Bottom": "Alinear abajo",
    "Align Center": "Alinear al centro",
    "Align Left": "Alinear a la izquierda",
    "Align Middle": "Alinear al medio",
    "Align Right": "Alinear a la derecha",
    "Align Selected": "Alinear selección",
    "Align Top": "Alinear arriba",
    "All": "Todos",
    "All locales": "Todos los idiomas",
    "All projects will be copied to iCloud. Initial sync may take time for large projects.": "Todos los proyectos se copiarán a iCloud. La sincronización inicial puede tardar con proyectos grandes.",
    "Alphabetically": "Alfabéticamente",
    "Angular": "Cónico",
    "App Info (shared across versions)": "Información de la app (compartida entre versiones)",
    "App Store Connect API documentation": "Documentación de la API de App Store Connect",
    "App Store Connect API key required": "Se requiere clave de API de App Store Connect",
    "App Store Connect rejects this if the selected app version is iPhone-only.": "App Store Connect lo rechaza si la versión seleccionada es solo para iPhone.",
    "Appearance": "Apariencia",
    "Applies to all locales for this version.": "Se aplica a todos los idiomas de esta versión.",
    "Are you sure you want to delete \"%@\"?": "¿Seguro que quieres eliminar «%@»?",
    "Are you sure you want to delete \"%@\"? This cannot be undone.": "¿Seguro que quieres eliminar «%@»? Esta acción no se puede deshacer.",
    "Are you sure you want to delete this screenshot?": "¿Seguro que quieres eliminar esta captura?",
    "Are you sure you want to reset \"%@\" using the \"%@\" template? All current rows and shapes will be replaced. This cannot be undone.": "¿Seguro que quieres restablecer «%1$@» usando la plantilla «%2$@»? Todas las filas y formas actuales se reemplazarán. Esta acción no se puede deshacer.",
    "Are you sure you want to reset \"%@\"? All rows and shapes will be removed. This cannot be undone.": "¿Seguro que quieres restablecer «%@»? Se eliminarán todas las filas y formas. Esta acción no se puede deshacer.",
    "ASC value": "Valor de ASC",
    "Ask before deleting rows and screenshots": "Preguntar antes de eliminar filas y capturas",
    "Ask each time": "Preguntar cada vez",
    "Attributions": "Atribuciones",
    "Auto": "Automático",
    "Auto-detected": "Detectado automáticamente",
    "Auto-Translate": "Traducir automáticamente",
    "Auto-Translate Missing Text": "Traducir automáticamente texto faltante",
    "%@ text": "Texto de %@",
    "Back": "Atrás",
    "Background": "Fondo",
    "Background Override": "Anulación de fondo",
    "Backup": "Copia de seguridad",
    "Backup failed (zip exited with status %d).": "Error al crear la copia (zip terminó con estado %d).",
    "Backup failed (zip exited with status %lld).": "Error al crear la copia (zip terminó con estado %lld).",
    "Backup saved successfully.": "Copia de seguridad guardada correctamente.",
    "Base": "Base",
    "Base text": "Texto base",
    "Blur": "Desenfoque",
    "Bold": "Negrita",
    "Borders": "Bordes",
    "Bring to Front": "Traer al frente",
    "By creation date": "Por fecha de creación",
    "Cancel": "Cancelar",
    "Cancel Upload": "Cancelar envío",
    "Center": "Centrar",
    "Center All": "Centrar todos",
    "Change All To": "Cambiar todo a",
    "Change Device": "Cambiar dispositivo",
    "Change Font Size": "Cambiar tamaño de fuente",
    "Changes here affect only %@. The base language text is shared across all locales — edits to other locales are stored as overrides.": "Los cambios aquí afectan solo a %@. El texto del idioma base es común a todos los idiomas — las ediciones en otros idiomas se guardan como anulaciones.",
    "Choose a template": "Elige una plantilla",
    "Choose or Drop Image": "Elige o suelta una imagen",
    "Choose…": "Elegir…",
    "Clear App Store Connect Credentials…": "Borrar credenciales de App Store Connect…",
    "Clear App Store Connect credentials?": "¿Borrar las credenciales de App Store Connect?",
    "Clear Credentials": "Borrar credenciales",
    "Clear export folder": "Quitar carpeta de exportación",
    "Clear Formatting": "Quitar formato",
    "Click bar to add stops": "Haz clic en la barra para añadir paradas",
    "Clip to Frame": "Recortar al marco",
    "Close": "Cerrar",
    "Color": "Color",
    "Compare Plans": "Comparar planes",
    "Connecting...": "Conectando…",
    "Connection": "Conexión",
    "Continue": "Continuar",
    "Continuous": "Continuo",
    "Copy": "Copiar",
    "Copy Details": "Copiar detalles",
    "Copy Text Style": "Copiar estilo de texto",
    "Copyright": "Copyright",
    "Create Backup…": "Crear copia de seguridad…",
    "Create or manage API keys": "Crear o gestionar claves de API",
    "Current Project": "Proyecto actual",
    "Current export folder: %@": "Carpeta de exportación actual: %@",
    "Custom": "Personalizado",
    "Custom color": "Color personalizado",
    "Cut": "Cortar",
    "Dark": "Oscuro",
    "Default device frame": "Marco de dispositivo predeterminado",
    "Default zoom level": "Nivel de zoom predeterminado",
    "Delete": "Eliminar",
    "Delete Project": "Eliminar proyecto",
    "Delete Project...": "Eliminar proyecto…",
    "Delete Row": "Eliminar fila",
    "Delete Screenshot": "Eliminar captura",
    "Delete Selected": "Eliminar selección",
    "Delete all": "Eliminar todo",
    "Delete locale": "Eliminar idioma",
    "Delete row": "Eliminar fila",
    "Deselect": "Deseleccionar",
    "Details": "Detalles",
    "Device": "Dispositivo",
    "Devices": "Dispositivos",
    "Disable iCloud Sync": "Desactivar sincronización con iCloud",
    "Disable outline": "Desactivar contorno",
    "Display Type": "Tipo de pantalla",
    "Distribute Horizontally": "Distribuir horizontalmente",
    "Distribute Vertically": "Distribuir verticalmente",
    "Done": "Hecho",
    "Double-click to reset": "Doble clic para restablecer",
    "Drop Image": "Soltar imagen",
    "Drop or paste an image to configure fill and opacity.": "Suelta o pega una imagen para configurar el relleno y la opacidad.",
    "Duplicate": "Duplicar",
    "Duplicate Project": "Duplicar proyecto",
    "Duplicate Project...": "Duplicar proyecto…",
    "Duplicate Row": "Duplicar fila",
    "Duplicate Screenshot": "Duplicar captura",
    "Duplicate row": "Duplicar fila",
    "Edit Translation Table...": "Editar tabla de traducción…",
    "Edit Translations": "Editar traducciones",
    "Edit the base language and each translated language side by side. Leave a cell empty to use the base language text.": "Edita el idioma base y cada idioma traducido en paralelo. Deja una celda vacía para usar el texto del idioma base.",
    "Edit translations manually or use Auto-Translate": "Edita las traducciones a mano o usa Traducción automática",
    "Editing %@": "Editando %@",
    "Enable iCloud Sync": "Activar sincronización con iCloud",
    "Enable outline": "Activar contorno",
    "Every version on this app is locked for review or live. Create a new version in App Store Connect, then refresh this wizard.": "Todas las versiones de esta app están bloqueadas para revisión o ya publicadas. Crea una nueva versión en App Store Connect y luego actualiza este asistente.",
    "Export": "Exportar",
    "Export All Screenshots to Folder...": "Exportar todas las capturas a una carpeta…",
    "Export Failed": "Error al exportar",
    "Export folder": "Carpeta de exportación",
    "Export Locale": "Exportar idioma",
    "Export Row": "Exportar fila",
    "Export Rows": "Exportar filas",
    "Export options": "Opciones de exportación",
    "Exporting Screenshots...": "Exportando capturas…",
    "Export…": "Exportar…",
    "Fill": "Rellenar",
    "Fill color": "Color de relleno",
    "Finish setup": "Finalizar configuración",
    "Fit": "Ajustar",
    "Fix required": "Corrección necesaria",
    "Focus on Selection": "Centrar en la selección",
    "Font": "Fuente",
    "Font size": "Tamaño de fuente",
    "for Android and iOS Apps": "para apps de Android e iOS",
    "Format": "Formato",
    "Free": "Gratis",
    "Free: %@": "Gratis: %@",
    "General": "General",
    "Get Started": "Empezar",
    "Gradient": "Degradado",
    "Hide All": "Ocultar todo",
    "Hide Borders": "Ocultar bordes",
    "Hide Devices": "Ocultar dispositivos",
    "Hide inspector": "Ocultar inspector",
    "Horizontal alignment": "Alineación horizontal",
    "Horizontally": "Horizontal",
    "iCloud is not available. Sign in to iCloud in System Settings.": "iCloud no está disponible. Inicia sesión en iCloud en Ajustes del sistema.",
    "iCloud Sync": "Sincronización con iCloud",
    "If a matching display type already has screenshots, they will be deleted and replaced. You'll be asked to confirm before anything is uploaded.": "Si ya hay capturas en un tipo de pantalla coincidente, se eliminarán y reemplazarán. Se te pedirá confirmación antes de enviar nada.",
    "Image": "Imagen",
    "Import File...": "Importar archivo…",
    "Imported": "Importada",
    "Included": "Incluido",
    "Inspector": "Inspector",
    "Italic": "Cursiva",
    "Leave a field empty to fall back to base language": "Deja un campo vacío para usar el idioma base",
    "Leave empty to use the base language text": "Déjalo vacío para usar el texto del idioma base",
    "Left": "Izquierda",
    "Legal": "Legal",
    "Letter Spacing": "Espaciado entre letras",
    "License: CC Attribution": "Licencia: CC Attribution",
    "Light": "Claro",
    "Line Spacing": "Interlineado",
    "Linear": "Lineal",
    "Locale": "Idioma",
    "Locale Editing": "Edición por idioma",
    "Locales": "Idiomas",
    "Looks valid": "Parece válido",
    "Manage Locales": "Gestionar idiomas",
    "Manage Locales...": "Gestionar idiomas…",
    "Match Size to Other Devices": "Igualar tamaño a otros dispositivos",
    "Medium": "Media",
    "Mode": "Modo",
    "More actions": "Más acciones",
    "Move Left": "Mover a la izquierda",
    "Move Right": "Mover a la derecha",
    "Move Row Down": "Mover fila abajo",
    "Move Row Up": "Mover fila arriba",
    "Name": "Nombre",
    "New Project": "Nuevo proyecto",
    "New Project...": "Nuevo proyecto…",
    "Next": "Siguiente",
    "Next Locale": "Siguiente idioma",
    "No Row Selected": "Ninguna fila seleccionada",
    "No Templates Available": "No hay plantillas disponibles",
    "No device": "Sin dispositivo",
    "No editable metadata for this locale.": "No hay metadatos editables para este idioma.",
    "No editable version available": "No hay versiones editables disponibles",
    "No matching App Store locale": "No hay idioma de App Store coincidente",
    "No rows selected": "No hay filas seleccionadas",
    "No text shapes in this project.": "No hay capas de texto en este proyecto.",
    "None": "Ninguno",
    "OK": "Aceptar",
    "One-time in-app purchase": "Compra única dentro de la app",
    "Open %@ in App Store Connect": "Abrir %@ en App Store Connect",
    "Open API Keys": "Abrir claves de API",
    "Open app in App Store Connect": "Abrir app en App Store Connect",
    "Open Export Folder": "Abrir carpeta de exportación",
    "Open in Finder": "Abrir en Finder",
    "Open Settings": "Abrir Ajustes",
    "Open System Settings": "Abrir Ajustes del sistema",
    "Orientation": "Orientación",
    "Outline": "Contorno",
    "Overridden": "Anulado",
    "Override background": "Anular fondo",
    "Override color": "Anular color",
    "Paste": "Pegar",
    "Paste Text Style": "Pegar estilo de texto",
    "Paste your SVG here...": "Pega tu SVG aquí…",
    "Pick custom font": "Elegir fuente personalizada",
    "Place After This One": "Colocar después de esta",
    "Place at End": "Colocar al final",
    "Plan": "Plan",
    "Points: %lld": "Puntos: %lld",
    "Preflight": "Comprobaciones previas",
    "Preset": "Predefinido",
    "Presets": "Predefinidos",
    "Previous Locale": "Idioma anterior",
    "Privacy Policy": "Política de privacidad",
    "Private key imported. App Store Connect lets you download a .p8 key only once, so keep the original file somewhere safe.": "Clave privada importada. App Store Connect solo permite descargar un archivo .p8 una vez, así que guarda el original en un lugar seguro.",
    "Pro: %@": "Pro: %@",
    "Project %@": "Proyecto %@",
    "Project actions": "Acciones de proyecto",
    "Project name": "Nombre del proyecto",
    "Project order": "Orden de proyectos",
    "Project storage": "Almacenamiento de proyectos",
    "Projects": "Proyectos",
    "Projects will be kept locally. Other Macs will no longer see updates.": "Los proyectos se conservarán localmente. Otros Macs ya no verán actualizaciones.",
    "Purchase": "Compra",
    "Purchase Status": "Estado de la compra",
    "Purchase type": "Tipo de compra",
    "Quick Look": "Vista rápida",
    "Radial": "Radial",
    "Re-Translate All Text...": "Retraducir todo el texto…",
    "Read-only": "Solo lectura",
    "Ready": "Listo",
    "Ready to test": "Listo para probar",
    "Refresh App Store data": "Actualizar datos de la App Store",
    "Regular": "Regular",
    "Remove": "Quitar",
    "Remove stop (min 2)": "Quitar parada (mínimo 2)",
    "Rename": "Renombrar",
    "Rename Project": "Renombrar proyecto",
    "Rename Project...": "Renombrar proyecto…",
    "Render Failed": "Error de renderizado",
    "Replace": "Reemplazar",
    "Replace All Text": "Reemplazar todo el texto",
    "Replace All Text…": "Reemplazar todo el texto…",
    "Replace Image": "Reemplazar imagen",
    "Replace Image...": "Reemplazar imagen…",
    "Replace SVG": "Reemplazar SVG",
    "Replace all %@ text with new translations?": "¿Reemplazar todo el texto de %@ con nuevas traducciones?",
    "Replace existing screenshots?": "¿Reemplazar las capturas existentes?",
    "Replace…": "Reemplazar…",
    "Reset": "Restablecer",
    "Reset All Images": "Restablecer todas las imágenes",
    "Reset Image": "Restablecer imagen",
    "Reset Project": "Restablecer proyecto",
    "Reset Project from Template": "Restablecer proyecto desde plantilla",
    "Reset Project...": "Restablecer proyecto…",
    "Reset Row": "Restablecer fila",
    "Reset all %@ text and image overrides?": "¿Restablecer todas las anulaciones de texto e imágenes de %@?",
    "Reset to defaults": "Restablecer valores por defecto",
    "Restore Original Aspect Ratio": "Restaurar proporción original",
    "Restore Purchase": "Restaurar compra",
    "Reveal in Finder after export": "Mostrar en Finder tras exportar",
    "RevenueCat isn’t configured": "RevenueCat no está configurado",
    "Reverse gradient": "Invertir degradado",
    "Revert to Base": "Volver al idioma base",
    "Revert to Base Language...": "Volver al idioma base…",
    "Review and upload plan": "Revisar plan de envío",
    "Right": "Derecha",
    "Row label": "Etiqueta de fila",
    "Rows": "Filas",
    "Rows per project": "Filas por proyecto",
    "Save & Continue": "Guardar y continuar",
    "Save as PNG...": "Guardar como PNG…",
    "Save Failed": "Error al guardar",
    "Screenshot Bro Pro is unlocked.": "Screenshot Bro Pro está desbloqueado.",
    "Screenshot Center": "Centro de capturas",
    "Screenshot Size": "Tamaño de captura",
    "Screenshots": "Capturas",
    "Screenshots per row": "Capturas por fila",
    "Search languages...": "Buscar idiomas…",
    "Select All": "Seleccionar todo",
    "Select a locale on the left to edit its metadata.": "Selecciona un idioma a la izquierda para editar sus metadatos.",
    "Select a row to edit its settings.": "Selecciona una fila para editar sus ajustes.",
    "Select a version": "Selecciona una versión",
    "Select an app": "Selecciona una app",
    "Select at least one row to preview and export.": "Selecciona al menos una fila para previsualizar y exportar.",
    "Selected uploads": "Envíos seleccionados",
    "Select…": "Seleccionar…",
    "Send to Back": "Enviar al fondo",
    "Setup": "Configuración",
    "Shapes": "Formas",
    "Show All": "Mostrar todo",
    "Show Borders": "Mostrar bordes",
    "Show Devices": "Mostrar dispositivos",
    "Show inspector": "Mostrar inspector",
    "Showcase": "Escaparate",
    "Size": "Tamaño",
    "Skipped items (%lld)": "Elementos omitidos (%lld)",
    "Source": "Origen",
    "Source %@ · %lld screenshot%@ · %@": "Origen %1$@ · %2$lld captura%3$@ · %4$@",
    "Source size": "Tamaño de origen",
    "Status": "Estado",
    "Step %lld": "Paso %lld",
    "Storage": "Almacenamiento",
    "Stretch": "Estirar",
    "Stretch across all screenshots": "Estirar por todas las capturas",
    "Style": "Estilo",
    "SVG custom color": "Color personalizado de SVG",
    "Switch to Base": "Cambiar al idioma base",
    "Sync with iCloud": "Sincronizar con iCloud",
    "Syncing via iCloud": "Sincronizando con iCloud",
    "Templates": "Plantillas",
    "Test Connection": "Probar conexión",
    "Testing lists one app from the account. If this passes but uploads fail, check that the API key can edit the specific app and version.": "La prueba lista una app de la cuenta. Si la prueba funciona pero los envíos fallan, comprueba que la clave de API puede editar esa app y versión concretas.",
    "Testing…": "Probando…",
    "Text": "Texto",
    "Text color": "Color del texto",
    "The first language is the base. Drag to reorder.": "El primer idioma es el base. Arrastra para reordenar.",
    "The required languages are not downloaded on your Mac.\n\nTo download them, go to:\nSystem Settings → General → Language & Region → Translation Languages\n\nThen download the languages you need and try again.": "Los idiomas necesarios no están descargados en este Mac.\n\nPara descargarlos, ve a:\nAjustes del sistema → General → Idioma y región → Idiomas de traducción\n\nLuego descarga los idiomas que necesites e inténtalo de nuevo.",
    "This applies translation from the base language to every text layer in %@ and replaces the current translated text.": "Esto traduce desde el idioma base a cada capa de texto en %@ y reemplaza el texto traducido actual.",
    "This removes all translated text and locale-specific image overrides for %@, so the project uses the base language text and images again.": "Esto elimina todas las traducciones y anulaciones de imagen específicas de %@, de modo que el proyecto vuelve a usar el texto e imágenes del idioma base.",
    "This removes all translated text and locale-specific image overrides for the current language, so the project uses the base language text and images again.": "Esto elimina todas las traducciones y anulaciones de imagen específicas del idioma actual, de modo que el proyecto vuelve a usar el texto e imágenes del idioma base.",
    "This removes the Issuer ID, Key ID, and imported private key from this Mac.": "Esto elimina el Issuer ID, el Key ID y la clave privada importada de este Mac.",
    "This Version": "Esta versión",
    "This version is %@ — screenshots can't be changed. Pick an editable version or create a new one in App Store Connect.": "Esta versión está en %@ — las capturas no se pueden cambiar. Elige una versión editable o crea una nueva en App Store Connect.",
    "This will remove all screenshots and shapes from \"%@\" and restore default settings.": "Esto eliminará todas las capturas y formas de «%@» y restaurará los ajustes por defecto.",
    "Tile": "Mosaico",
    "To All Screenshots": "A todas las capturas",
    "To All Screenshots on the Left": "A todas las capturas a la izquierda",
    "To All Screenshots on the Right": "A todas las capturas a la derecha",
    "Translate": "Traducir",
    "Translate Selected": "Traducir selección",
    "Translate into %@": "Traducir al %@",
    "Translate selected text layers into %@": "Traducir las capas de texto seleccionadas al %@",
    "Translating text…": "Traduciendo texto…",
    "Translation Languages Not Available": "Idiomas de traducción no disponibles",
    "Type": "Tipo",
    "Unlimited": "Ilimitado",
    "Unlimited projects": "Proyectos ilimitados",
    "Unlimited rows per project": "Filas ilimitadas por proyecto",
    "Unlimited screenshots per row": "Capturas ilimitadas por fila",
    "Unlock all projects, rows, and templates": "Desbloquea todos los proyectos, filas y plantillas",
    "Unlock Screenshot Bro Pro": "Desbloquear Screenshot Bro Pro",
    "Upgrade": "Actualizar",
    "Upgrade to Pro": "Pasar a Pro",
    "Upload": "Enviar",
    "Upload and Replace": "Enviar y reemplazar",
    "Upload as": "Enviar como",
    "Upload complete": "Envío completado",
    "Upload failed": "Error al enviar",
    "Upload target": "Destino del envío",
    "Upload to App Store Connect": "Enviar a App Store Connect",
    "Uppercase": "Mayúsculas",
    "Use an App Store Connect API key with access to edit app metadata. Account Holder, Admin, or App Manager roles are typical for screenshot uploads.": "Usa una clave de API de App Store Connect con permisos para editar los metadatos de la app. Los roles Account Holder, Admin o App Manager suelen ser suficientes para enviar capturas.",
    "Use Custom Color": "Usar color personalizado",
    "Use custom color for SVG": "Usar color personalizado para SVG",
    "Use detected (%@)": "Usar detectado (%@)",
    "Use Edit Translations for a side-by-side view": "Usa Editar traducciones para una vista en paralelo",
    "Values are saved automatically on this Mac. The private key is stored in Keychain.": "Los valores se guardan automáticamente en este Mac. La clave privada se almacena en el Llavero.",
    "Version": "Versión",
    "Vertical alignment": "Alineación vertical",
    "Vertically": "Vertical",
    "View on Figma Community": "Ver en Figma Community",
    "View on Sketchfab": "Ver en Sketchfab",
    "Visibility": "Visibilidad",
    "Watch style": "Estilo de reloj",
    "When set, Cmd+E exports directly to this folder without prompting.": "Cuando está establecida, Cmd+E exporta directamente a esta carpeta sin preguntar.",
    "Your unlock is managed by the App Store for this Apple Account.": "Tu desbloqueo está gestionado por el App Store para esta cuenta de Apple.",
    "Zoom": "Zoom",
    "Zoom In": "Ampliar",
    "Zoom Out": "Reducir",
    "Zoom options": "Opciones de zoom",

    # Keys extracted by Xcode after the first pass (model labels, error
    # messages, confirmation strings, etc.).
    "Rectangle": "Rectángulo",
    "Rectangles": "Rectángulos",
    "Circle": "Círculo",
    "Circles": "Círculos",
    "Star": "Estrella",
    "Stars": "Estrellas",
    "Images": "Imágenes",
    "SVGs": "SVGs",
    "Invisible": "Invisible",
    "Android Phone": "Teléfono Android",
    "Android Tablet": "Tablet Android",
    "Abstract Pixel 9": "Pixel 9 abstracto",
    "Landscape": "Horizontal",
    "Portrait": "Vertical",
    "Untitled Row": "Fila sin título",
    "Save": "Guardar",
    "Debug": "Depuración",
    "Release": "Release",
    "Deselect All": "Deseleccionar todo",
    "Override Existing": "Sobrescribir existente",
    "screenshot": "captura",
    "screenshots": "capturas",
    "Select": "Seleccionar",
    "selected folder": "carpeta seleccionada",
    "%lld %@ exported": "%1$lld %2$@ exportada(s)",
    "%lld %@ exported · %@": "%1$lld %2$@ exportada(s) · %3$@",
    "Export complete": "Exportación completada",
    "Export failed": "Error al exportar",

    # NSSavePanel / NSOpenPanel
    "Choose a folder for exported screenshots": "Elige una carpeta para las capturas exportadas",

    # SVG errors
    "SVG content is too large (max 512 KB)": "El contenido SVG es demasiado grande (máximo 512 KB)",
    "Not a valid SVG — must contain an <svg> element": "SVG no válido — debe contener un elemento <svg>",
    "Could not render SVG — check for syntax errors": "No se pudo renderizar el SVG — comprueba si hay errores de sintaxis",
    "Invalid SVG content": "Contenido SVG no válido",

    # Render/preview errors
    "Could not render screenshot for preview.": "No se pudo renderizar la captura para previsualización.",
    "Could not write preview file: %@": "No se pudo escribir el archivo de previsualización: %@",
    "Failed to render screenshot": "Error al renderizar la captura",

    # Export errors
    "Could not export row image: %@": "No se pudo exportar la imagen de la fila: %@",
    "Could not export row screenshots: %@": "No se pudieron exportar las capturas de la fila: %@",
    "Failed to render row %lld": "Error al renderizar la fila %lld",
    "Failed to remember export folder": "No se pudo recordar la carpeta de exportación",

    # AppState save errors
    "Failed to save project index: %@": "Error al guardar el índice de proyectos: %@",
    "Failed to save project: %@": "Error al guardar el proyecto: %@",
    "Failed to %@: could not encode image.": "Error al %@: no se pudo codificar la imagen.",
    "Failed to %@: %@": "Error al %1$@: %2$@",
    "Failed to create project from template \"%@\". The template data could not be loaded.": "Error al crear el proyecto desde la plantilla «%@». No se pudieron cargar los datos de la plantilla.",

    # App Store Connect API
    "Invalid request URL.": "URL de solicitud no válida.",
    "App Store Connect returned %lld: %@": "App Store Connect devolvió %1$lld: %2$@",
    "Response decoding failed: %@": "Fallo al decodificar la respuesta: %@",
    "Connected. First app: %@": "Conectado. Primera app: %@",
    "Connected. No apps found on this account yet.": "Conectado. Aún no se encontraron apps en esta cuenta.",
    "not editable": "no editable",

    # App Store Connect auth
    "Issuer ID, Key ID, and private key are required.": "Se requieren Issuer ID, Key ID y clave privada.",
    "Could not parse the private key. Make sure it's a valid .p8 file downloaded from App Store Connect.": "No se pudo analizar la clave privada. Asegúrate de que sea un archivo .p8 válido descargado de App Store Connect.",
    "Failed to sign the JWT token.": "Error al firmar el token JWT.",

    # Keychain
    "Keychain save failed (status %d)": "Error al guardar en el Llavero (estado %d)",

    # iCloud
    "iCloud container is not available. Make sure you're signed into iCloud.": "El contenedor de iCloud no está disponible. Asegúrate de haber iniciado sesión en iCloud.",

    # Upload flow
    "Could not render screenshot %lld for %@ (%@) in %@. Check that this row previews correctly in the editor, then try the upload again.": "No se pudo renderizar la captura %1$lld para %2$@ (%3$@) en %4$@. Comprueba que esta fila se previsualiza correctamente en el editor y vuelve a intentar el envío.",
    "No rows selected for upload.": "No hay filas seleccionadas para enviar.",
    "Could not render %@ · %@ · screenshot %lld.": "No se pudo renderizar %1$@ · %2$@ · captura %3$lld.",
    "Network request failed: %@": "Fallo en la solicitud de red: %@",
    "%@ is not allowed for this app/version.": "%@ no está permitido para esta app/versión.",
    "App Store Connect returned %lld while trying to %@.": "App Store Connect devolvió %1$lld al intentar %2$@.",
    "Upload failed while trying to %@.": "Fallo al enviar durante %@.",
    "Could not create the screenshot set for %@ (%@) in %@.": "No se pudo crear el conjunto de capturas para %1$@ (%2$@) en %3$@.",
    "App Store Connect does not allow %@ (%@) for this app version/localization. This usually means the selected app version does not support that device family, such as uploading iPad screenshots for an iPhone-only app, or App Store Connect does not accept this display type for the selected platform.": "App Store Connect no permite %1$@ (%2$@) para esta versión/idioma. Normalmente significa que la versión seleccionada no admite esa familia de dispositivos, por ejemplo subir capturas de iPad a una app solo para iPhone, o que App Store Connect no acepta este tipo de pantalla para la plataforma elegida.",
    "Disable this row, choose a display type that App Store Connect accepts for this app, or update the app's device support before retrying.": "Desactiva esta fila, elige un tipo de pantalla que App Store Connect acepte para esta app o actualiza la compatibilidad de dispositivos antes de reintentar.",
    "The existing %@ screenshot set for %@ may already have been deleted. After fixing the issue, re-run the upload to refill that set.": "El conjunto de capturas %1$@ para %2$@ puede haber sido eliminado. Tras corregir el problema, vuelve a ejecutar el envío para rellenar ese conjunto.",
    "Original response: %@": "Respuesta original: %@",
    "Could not %@ for %@ (%@) in %@.": "No se pudo %1$@ para %2$@ (%3$@) en %4$@.",
    "App Store Connect rejected the request because the API key is not authorized for this app or action. Check that the key has access to this app and enough App Store Connect permissions to edit app metadata.": "App Store Connect rechazó la solicitud porque la clave de API no está autorizada para esta app o acción. Comprueba que la clave tenga acceso a esta app y permisos suficientes en App Store Connect para editar los metadatos.",
    "App Store Connect did not accept the request. Check the selected app, version, display type, and locale, then retry.": "App Store Connect no aceptó la solicitud. Comprueba la app, la versión, el tipo de pantalla y el idioma seleccionados y vuelve a intentarlo.",

    # Store / RevenueCat
    "Failed to refresh purchase status: %@": "No se pudo actualizar el estado de compra: %@",
    "Screenshot Bro Pro is unlocked and ready to use.": "Screenshot Bro Pro está desbloqueado y listo para usar.",
    "Purchase completed, but RevenueCat did not grant access. Check the entitlement or product mapping in RevenueCat.": "La compra se completó pero RevenueCat no concedió acceso. Revisa la configuración de entitlement o producto en RevenueCat.",
    "Purchase failed: %@": "Error en la compra: %@",
    "Restore failed: %@": "Error al restaurar: %@",
    "RevenueCat is not configured.": "RevenueCat no está configurado.",
    "Your Screenshot Bro Pro purchase was restored.": "Tu compra de Screenshot Bro Pro se ha restaurado.",
    "No Screenshot Bro Pro purchase was found for this Apple Account.": "No se encontró ninguna compra de Screenshot Bro Pro para esta cuenta de Apple.",
    "RevenueCat API key is missing. Set REVENUECAT_API_KEY in the app environment or Info.plist.": "Falta la clave de API de RevenueCat. Configura REVENUECAT_API_KEY en el entorno de la app o en Info.plist.",
    "RevenueCat is configured with a Test Store API key. Replace it with your Apple public SDK key before shipping.": "RevenueCat está configurado con una clave de API de Test Store. Sustitúyela por tu clave pública SDK de Apple antes de publicar.",

    # Templates / Projects (debug-ish, internal tools but present)
    "Manage Projects...": "Gestionar proyectos…",
    "New Template...": "Nueva plantilla…",
    "Open Template": "Abrir plantilla",
    "Save Current Project as Template": "Guardar proyecto actual como plantilla",
    "Save as New Template": "Guardar como nueva plantilla",
    "Enter a directory name for the template (e.g. my_template).": "Introduce un nombre de carpeta para la plantilla (p. ej. mi_plantilla).",
    "Regenerate All Previews": "Regenerar todas las previsualizaciones",
    "Delete %lld project%@?": "¿Eliminar %1$lld proyecto%2$@?",
    "Delete %lld selected": "Eliminar %lld seleccionado(s)",
    "%lld projects": "%lld proyectos",
    "Badged templates are included in non-debug builds.": "Las plantillas con insignia se incluyen en compilaciones que no son de depuración.",
    "Switch project": "Cambiar de proyecto",
    "Template name": "Nombre de la plantilla",
    "Upload to App Store Connect…": "Enviar a App Store Connect…",
    "Template Error": "Error de plantilla",
    "Show Onboarding...": "Mostrar introducción…",
    "This cannot be undone.": "Esta acción no se puede deshacer.",

    # Second-pass extractions from App Store Connect settings, toolbar, backgrounds.
    "System": "Sistema",
    "Upload failed: %@": "Error al enviar: %@",
    "Could not refresh locales: %@": "No se pudieron actualizar los idiomas: %@",
    "Failed to save metadata: %@": "Error al guardar los metadatos: %@",
    "Fix the preflight errors before uploading.": "Corrige los errores de comprobación antes de enviar.",
    "No rows × locales are selected.": "No se ha seleccionado ninguna combinación de filas × idiomas.",
    "Upload cancelled. Any set that was already being replaced may be empty in App Store Connect — re-run the upload to refill it.": "Envío cancelado. Cualquier conjunto que ya se estuviese reemplazando puede estar vacío en App Store Connect — vuelve a enviar para rellenarlo.",
    "Row": "Fila",
    "No display type selected": "No se ha seleccionado un tipo de pantalla",
    "No App Store locale selected": "No se ha seleccionado un idioma de la App Store",
    "Unchecked": "No marcado",
    "Skipped": "Omitido",
    "Existing screenshots in each matching display type set will be deleted and replaced. ": "Las capturas existentes de cada tipo de pantalla coincidente se eliminarán y reemplazarán. ",
    "%lld %@ will be uploaded across %lld %@ and %lld %@. ": "Se enviarán %1$lld %2$@ en %3$lld %4$@ y %5$lld %6$@. ",
    "%lld %@ across %lld %@": "%1$lld %2$@ en %3$lld %4$@",
    "%lld %@ across %lld %@ · %@": "%1$lld %2$@ en %3$lld %4$@ · %5$@",
    "screenshot": "captura",
    "screenshots": "capturas",
    "set": "conjunto",
    "sets": "conjuntos",
    "locale": "idioma",
    "locales": "idiomas",

    # ASC Settings setup items
    "Required UUID from App Store Connect": "UUID necesario de App Store Connect",
    "Required 10-character key ID": "Key ID de 10 caracteres necesario",
    ".p8 key imported": "Clave .p8 importada",
    "Import the .p8 file downloaded when the key was created": "Importa el archivo .p8 descargado al crear la clave",
    "Import the .p8 file downloaded when the key was created.": "Importa el archivo .p8 descargado al crear la clave.",
    "Private key": "Clave privada",
    "Last test passed": "Última prueba superada",
    "Last test failed": "Última prueba fallida",
    "Not tested yet": "Aún no se ha probado",
    "Available after setup is complete": "Disponible cuando la configuración esté completa",
    "Configuration is complete.": "La configuración está completa.",
    "Missing: %@.": "Falta: %@.",
    "Test the connection before uploading screenshots.": "Prueba la conexión antes de enviar capturas.",
    "Paste the Issuer ID from the API Keys page.": "Pega el Issuer ID desde la página de claves de API.",
    "Issuer ID should be a UUID.": "El Issuer ID debe ser un UUID.",
    "Paste the 10-character Key ID.": "Pega el Key ID de 10 caracteres.",
    "Key ID is usually 10 uppercase letters and numbers.": "El Key ID suele tener 10 letras mayúsculas y números.",
    "That doesn't look like a valid .p8 private key.": "Esto no parece una clave privada .p8 válida.",
    "Could not import the private key: %@": "No se pudo importar la clave privada: %@",
    "%@ Check that the Issuer ID, Key ID, private key, and API key permissions match the App Store Connect key.": "%@ Comprueba que el Issuer ID, el Key ID, la clave privada y los permisos de la clave de API coinciden con la clave de App Store Connect.",

    # Metadata form labels (ASC upload view)
    "App Name": "Nombre de la app",
    "Subtitle": "Subtítulo",
    "Privacy Policy URL": "URL de política de privacidad",
    "Promotional Text": "Texto promocional",
    "Description": "Descripción",
    "Keywords (comma-separated)": "Palabras clave (separadas por comas)",
    "What's New": "Novedades",
    "Support URL": "URL de soporte",
    "Marketing URL": "URL de marketing",

    # ActionButton tooltips (now LocalizedStringKey)
    "Preview": "Previsualizar",
    "Download": "Descargar",
    "Move left": "Mover a la izquierda",
    "Move right": "Mover a la derecha",
    "Move up": "Subir",
    "Move down": "Bajar",
    "Reset row": "Restablecer fila",
    "Deselect all (Esc)": "Deseleccionar todo (Esc)",
    "Deselect shape (Esc)": "Deseleccionar forma (Esc)",
    "Bring to front (⇧⌘])": "Traer al frente (⇧⌘])",
    "Send to back (⇧⌘[)": "Enviar al fondo (⇧⌘[)",
    "Duplicate (⌘D)": "Duplicar (⌘D)",
    "Delete (⌫)": "Eliminar (⌫)",
    "Reset to default locale image": "Restablecer imagen del idioma por defecto",
    "Reset locale override": "Restablecer anulación de idioma",
    "Reset %@": "Restablecer %@",
    "Reset 3D device rotation": "Restablecer rotación 3D del dispositivo",
    "Choose Image": "Elegir imagen",

    # ShapePropertiesControlGroup labels (now LocalizedStringKey)
    "Opacity": "Opacidad",
    "Rotation": "Rotación",
    "Radius": "Radio",
    "Width": "Anchura",
    "Spacing": "Espaciado",
    "Offset": "Desplazamiento",
    "Scale": "Escala",
    "Pitch": "Inclinación",
    "Yaw": "Guiñada",
    "Points": "Puntos",
    "X": "X",
    "Y": "Y",

    # Manual language override picker (General settings)
    "Language": "Idioma",
    "Restart to change language": "Reinicia para cambiar el idioma",
    "Restart Now": "Reiniciar ahora",
    "Later": "Más tarde",
    "The interface language will switch the next time Screenshot Bro launches.": "El idioma de la interfaz cambiará la próxima vez que se abra Screenshot Bro.",
}


def collect_extracted_keys() -> set[str]:
    """Read Xcode's .stringsdata outputs for the Localizable table."""
    keys = set()
    for sd in glob.glob(STRINGSDATA_GLOB):
        try:
            payload = json.loads(Path(sd).read_text())
        except Exception:
            continue
        for table, entries in payload.get("tables", {}).items():
            if table != "Localizable":
                continue
            for entry in entries:
                if key := entry.get("key"):
                    keys.add(key)
    return keys


def main():
    data = json.loads(CATALOG.read_text())
    strings = data["strings"]

    # Merge any keys that Xcode extracted but didn't land in the catalog.
    merged = 0
    for key in collect_extracted_keys():
        if key not in strings:
            strings[key] = {}
            merged += 1

    added = 0
    kept = 0
    missing = []

    for key, entry in strings.items():
        locs = entry.setdefault("localizations", {})
        if "es" in locs:
            kept += 1
            continue
        if key in KEEP_AS_IS:
            # Mirror the English source as Spanish so Xcode shows 100% coverage.
            locs["es"] = {
                "stringUnit": {"state": "translated", "value": key},
            }
            added += 1
            continue
        if key in ES:
            locs["es"] = {
                "stringUnit": {"state": "translated", "value": ES[key]},
            }
            added += 1
            continue
        missing.append(key)

    CATALOG.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n")

    print(f"Merged from stringsdata: {merged}")
    print(f"Added Spanish: {added}")
    print(f"Already translated: {kept}")
    print(f"Missing translations: {len(missing)}")
    for k in missing:
        print(f"  - {k!r}")
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
